version: '3.8'
services:
  web: 
    image: g1uliax/m347:kn02b-web
    container_name: m347-kn04b-web
    ports:
      - 80:80
    networks:
      - kn04b

  db: 
    image: mariadb:latest
    container_name: m347-kn04b-db
    ports:
      - 3306:3306
    environment:
      MARIADB_ROOT_PASSWORD: 1234
      MARIADB_DATABASE: m347db
      MARIADB_USER: admin
      MARIADB_PASSWORD: 1234
    networks:
      - kn04b
      
networks:
  kn04b:
    name: kn04b
    driver: bridge
    ipam: 
      config:
        - subnet: 172.20.0.0/16
          ip_range: 172.20.5.0/24
          gateway: 172.20.5.254


  


